CREATE TABLE users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    account VARCHAR(64) NOT NULL,
    pwd_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(32) NOT NULL,
    abstract VARCHAR(128) NOT NULL DEFAULT '',
    avatar VARCHAR(256) NOT NULL DEFAULT '',
    ip VARCHAR(45) NOT NULL DEFAULT '',
    addr VARCHAR(128) NOT NULL DEFAULT '',
    role TINYINT UNSIGNED NOT NULL DEFAULT 2,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    open_id VARCHAR(128) NULL,
    register_source VARCHAR(32) NOT NULL DEFAULT 'account',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY ux_users_account (account),
    UNIQUE KEY ux_users_open_id (open_id),
    CONSTRAINT ck_users_role CHECK (role IN (1, 2)),
    CONSTRAINT ck_users_status CHECK (status IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE user_confs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    recall_message VARCHAR(32) NOT NULL DEFAULT '',
    friend_online TINYINT(1) NOT NULL DEFAULT 1,
    sound TINYINT(1) NOT NULL DEFAULT 1,
    secure_link TINYINT(1) NOT NULL DEFAULT 1,
    save_pwd TINYINT(1) NOT NULL DEFAULT 0,
    search_user TINYINT UNSIGNED NOT NULL DEFAULT 1,
    verification TINYINT UNSIGNED NOT NULL DEFAULT 2,
    verification_question JSON NULL,
    curtail_chat TINYINT(1) NOT NULL DEFAULT 0,
    add_user TINYINT(1) NOT NULL DEFAULT 0,
    create_group TINYINT(1) NOT NULL DEFAULT 0,
    in_group_chat TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY ux_user_confs_user (user_id),
    CONSTRAINT ck_user_confs_friend_online CHECK (friend_online IN (0, 1)),
    CONSTRAINT ck_user_confs_sound CHECK (sound IN (0, 1)),
    CONSTRAINT ck_user_confs_secure_link CHECK (secure_link IN (0, 1)),
    CONSTRAINT ck_user_confs_save_pwd CHECK (save_pwd IN (0, 1)),
    CONSTRAINT ck_user_confs_search_user CHECK (search_user BETWEEN 0 AND 2),
    CONSTRAINT ck_user_confs_verification CHECK (verification BETWEEN 0 AND 4),
    CONSTRAINT ck_user_confs_curtail_chat CHECK (curtail_chat IN (0, 1)),
    CONSTRAINT ck_user_confs_add_user CHECK (add_user IN (0, 1)),
    CONSTRAINT ck_user_confs_create_group CHECK (create_group IN (0, 1)),
    CONSTRAINT ck_user_confs_in_group_chat CHECK (in_group_chat IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
